/**
 * iOS standalone launch (splash) screens. iOS does not generate launch screens
 * from the web app manifest (that's Android/Chrome behavior) — it requires
 * `apple-touch-startup-image` links matched by device media queries.
 *
 * The PNGs are generated by `scripts/generate-pwa-assets.py`; add a device
 * here and regenerate when new Apple device sizes matter.
 */

export interface StartupImage {
  width: number;
  height: number;
  media?: string;
}

export const STARTUP_IMAGES: StartupImage[] = [
  // iPhones (portrait)
  { width: 1290, height: 2796, media: "(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3)" },
  { width: 1179, height: 2556, media: "(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3)" },
  { width: 1284, height: 2778, media: "(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3)" },
  { width: 1170, height: 2532, media: "(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3)" },
  { width: 1242, height: 2688, media: "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3)" },
  { width: 828, height: 1792, media: "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2)" },
  { width: 1125, height: 2436, media: "(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3)" },
  { width: 750, height: 1334, media: "(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2)" },
  { width: 640, height: 1136, media: "(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)" },
  // iPads (portrait + landscape)
  { width: 2048, height: 2732, media: "(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" },
  { width: 2732, height: 2048, media: "(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)" },
  { width: 1668, height: 2388, media: "(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" },
  { width: 2388, height: 1668, media: "(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)" },
  { width: 1668, height: 2224, media: "(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" },
  { width: 2224, height: 1668, media: "(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)" },
  { width: 1640, height: 2360, media: "(device-width: 820px) and (device-height: 1180px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" },
  { width: 2360, height: 1640, media: "(device-width: 820px) and (device-height: 1180px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)" },
  { width: 1536, height: 2048, media: "(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" },
  { width: 2048, height: 1536, media: "(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)" },
  // Universal fallback for devices not covered above
  { width: 1179, height: 2556 },
];

export function appleStartupImageLinks() {
  return STARTUP_IMAGES.map(({ width, height, media }) => ({
    rel: "apple-touch-startup-image" as const,
    href: `/splash-${width}x${height}.png`,
    ...(media ? { media } : {}),
  }));
}
